language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"petar",pwd:"admin",roles:["readWrite"]});'

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"petar",pwd:"admin",roles:["readWrite"]});'
